### VM BOX NAME -> centos7 (check readme file for box URL)
Vagrant.configure("2") do |config|
  config.vm.box = "centos7"
  config.vm.define "centos7" do |centos7|
     centos7.vm.provider :libvirt do |domain|
       domain.memory = 6096
       domain.cpus = 4
       domain.nested = true
       domain.volume_cache = 'none'
     end
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.synced_folder "./work", "/work",
      owner: "vagrant", group: "vagrant"
  end
  config.vm.network "public_network", :bridge => 'br-pxe', :dev => 'br-pxe' , :type => "bridge" , :ip => "172.31.81.130" , :netmask => "255.255.255.0"
end
